# Generated by Django 5.0.7 on 2024-08-04 11:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
