# Generated by Django 5.0.7 on 2024-08-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_person_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='height',
            field=models.CharField(max_length=100),
        ),
    ]
