# Generated by Django 5.0.7 on 2024-08-04 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_person_height'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='height',
        ),
    ]
