# Generated by Django 5.0.7 on 2024-08-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_person_height'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='height',
            field=models.IntegerField(default=0),
        ),
    ]
